# in the name of god  #بسم الله الرحمن الرحیم 
#!/usr/bin/env python3
#-*- coding: utf-8 -*-
"""
Created on Fri Jul 31 21:49:17 2020
@author: parseh
"""
# Form implementation generated from reading ui file 'TITA-DO.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pickle
from PyQt5 import QtCore, QtGui, QtWidgets

# start class Ui mainWindows
class Ui_MainWindow(object):
    # start funcion  setup Ui که اندازه و مختصات آبجکت هارا نشان میدهد
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("TITA-DO")
        MainWindow.resize(767, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(20, 420, 88, 34))
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setObjectName("ok")
        self.ENTER_TEXT = QtWidgets.QLineEdit(self.centralwidget)
        self.ENTER_TEXT.setGeometry(QtCore.QRect(150, 420, 581, 31))
        self.ENTER_TEXT.setText("")
        self.ENTER_TEXT.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.ENTER_TEXT.setObjectName("ENTER_TEXT")
        self.lable = QtWidgets.QLabel(self.centralwidget)
        self.lable.setGeometry(QtCore.QRect(310, 20, 151, 31))
        self.lable.setTextFormat(QtCore.Qt.MarkdownText)
        self.lable.setObjectName("lable")
        self.lable_2 = QtWidgets.QLabel(self.centralwidget)
        self.lable_2.setGeometry(QtCore.QRect(380, 50, 111, 31))
        self.lable_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.lable_2.setObjectName("lable_2")
        self.lable_3 = QtWidgets.QLabel(self.centralwidget)
        self.lable_3.setGeometry(QtCore.QRect(460, 30, 111, 31))
        self.lable_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.lable_3.setObjectName("lable_3")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(60, 120, 651, 231))
        self.log.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.log.setPlaceholderText("")
        self.log.setObjectName("log")
        self.log.raise_()
        self.ENTER_TEXT.raise_()
        self.ok.raise_()
        self.lable.raise_()
        self.lable_2.raise_()
        self.lable_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # --> self.. این قسمت نشان دهنده استفاده و سیگنال دهی را نشان میدهد 
        self.retranslateUi(MainWindow)
       # ok همان run است در اینجا اشاره می کند به اینکه اگر بر روی این کلیک شد تابع دریافت اطلاعات اجرا شود
        self.ok.clicked.connect(self.get_data)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    # start funcion get_data 
    def get_data(self):
        print(self.ENTER_TEXT.text())
        File = open('data.TOD', 'wb')
        pickle.dump(self.ENTER_TEXT.text(), File)
        File.close()

        file = open('data.TOD', 'rb')
        data = pickle.load(file)
        file.close()
        #print(data)
        self.log.append(data)


    # start funcion retanslateUi مربوط به نام های نمایشی
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("TITA-DO", "TITA-DO"))
        self.ok.setText(_translate("TITA-DO", "RUN"))
        self.ENTER_TEXT.setPlaceholderText(_translate("MainWindow", "TODO"))
        self.lable.setText(_translate("TITA-DO", " # TITA-DO"))
        self.lable_2.setText(_translate("TITA-DO", "#### BETA VERSION"))
        self.lable_3.setText(_translate("TITA-DO", "***0.10***"))


# نمایش داده شدن 
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


